### ISSUE TITLE
用户地址显示为"???"

### ISSUE THREAD

**Issue by xmalll** [ACT-Monster/ACT-Show#13]
http://192.168.7.117:6789/stackoverflow/showUser?userId=2243978
该用户在搜索界面和个人信息界面的地址均显示为"???"

**Comment by luckcul** [comment]
@yjiafei 
数据为什么会显示"???"
`MATCH (n:User) where n.Id= '2243978' RETURN n `
`Location	???`

**Comment by Runingtime** [comment]
原始数据就是三个问号，是用户自己填的
