### ISSUE TITLE
搜索页面-默认情况为搜索“javascript,css”

### ISSUE THREAD

**Issue by Jasmine-DJ-420** [ACT-Monster/ACT-Show#15]
如果输入空白，可以直接显示数据库总数而不显示搜索结果。默认搜索“javascript,css”感觉并不科学。

**Comment by luckcul** [comment]
默认情况下，是只显示用户总数比较好，还是同时也在下面显示一个所有用户的列表？

**Comment by Runingtime** [comment]
建议先不显示任何信息，类似于百度首页

**Comment by Jasmine-DJ-420** [comment]
可以参考Github检索用户时的显示，个人认为显示总数比较好，显示用户列表没有本质意义。

**Comment by ChenXuhan** [comment]
比较赞同只显示总数，不显示用户列表，查询所有用户的时间太长了，首页就要刷很长时间，影响用户体验。
