### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by Runingtime** [ACT-Monster/ACT-Show#16]
1.字体的字号调小一些
2.去除默认搜索JavaScript、css
3.个人信息的字段开头字母大写，如Platform
4.skills上下合并到一栏
5. aboutme太长会有错位http://192.168.7.117:6789/stackoverflow/showUser?userId=5014067
6.搜索结果中若用户标签太多需要折叠显示

**Comment by ChenXuhan** [comment]
这个About Me显示的效果跟设置的是一样的，如果觉得不满意，可以提一下如何显示的建议。
