### ISSUE TITLE
数据概览-GiHub增长趋势

### ISSUE THREAD

**Issue by Jasmine-DJ-420** [ACT-Monster/ACT-Show#18]
横轴时间坐标有问题，有两个2016，且9.5号出现的地方有待商榷。

**Comment by ChenXuhan** [comment]
后者表示的是2016年9月5日，因为字符串长度较长，所以分两行显示了

**Comment by Jasmine-DJ-420** [comment]
我认为把2016和2016.9.5分开显示有待商榷

**Comment by Runingtime** [comment]
可以把9.5去掉。因为最上面已经写了截止日期了

**Comment by ChenXuhan** [comment]
如果图上不谢截止时间的话，很容易造成误解，以为是某年全年完整的统计
