### ISSUE TITLE
StackOverflow也可以加上所在地分布

### ISSUE THREAD

**Issue by sunflower93** [ACT-Monster/ACT-Show#20]
我们的数据库中有5,987,285SO用户有地理位置信息，可以做地区分布展示。

**Comment by ChenXuhan** [comment]
这个问题，由于Stackoverflow的地理位置信息需要解析，之前被搁置了，现在可以考虑

**Comment by Runingtime** [comment]
这个自动解析国家比较困难，不像其他平台有country code，SO不知道有啥好的办法么

**Comment by luckcul** [comment]
@yjiafei

**Comment by ghost** [comment]
so上填写国家信息没有固定的顺序和格式，也不会检测填写地址是否非法，每个国家的名字也不唯一，如美国可以写为USA或America
