### ISSUE TITLE
雷达图的端点显示不完全且与分数存在重叠

### ISSUE THREAD

**Issue by xmalll** [ACT-Monster/ACT-Show#22]
http://192.168.7.117:6789/stackoverflow/showUser?userId=511147
该用户的技能雷达图右侧端点facebook后的文字被遮盖
上端点css与评分14重叠

**Comment by ChenXuhan** [comment]
好的，发现了

**Comment by zhouqilin1993** [comment]
http://192.168.7.117:6789/stackoverflow/showUser?userId=6448007
雷达图中textarea显示不完全
