### ISSUE TITLE
数据概览图的问题

### ISSUE THREAD

**Issue by ghost** [ACT-Monster/ACT-Show#23]
so部分节点用空心圆表示了，但是有些没有
so第二张图，纵轴应该为answer数目
github的所有坐标图和so的部分坐标图，没有动态出现的竖线

**Comment by ChenXuhan** [comment]
都需要竖线吗？那个本来就没有竖线

**Comment by ChenXuhan** [comment]
我都添加上竖线了，其他问题也已改过来了
