### ISSUE TITLE
搜索页面最下面页码的风格建议

### ISSUE THREAD

**Issue by zhouqilin1993** [ACT-Monster/ACT-Show#31]
<<  1 >> 共12345页
这样的风格太简单，不便于使用

如题，这样的页面导览感觉不好看，也不是很方便使用，可以用传统的方案：
|<  << 1 2 **3** 4 5 6 >>  >|   跳转到第X页，共XXX页

**Comment by ChenXuhan** [comment]
关于如何翻页问题，收集意见，最好能够的带一个统一的意见

**Comment by luckcul** [comment]
认为这种形式比较好

上一页 6 7 8 9 10 **11** 12 13 14 15 下一页 

感觉没有必要添加页码跳转，返回首页和末页。
