### ISSUE TITLE
最下端Question(4)显示错误

### ISSUE THREAD

**Issue by zhouqilin1993** [ACT-Monster/ACT-Show#32]
http://192.168.7.117:6789/stackoverflow/showUser?userId=6448007
如题，最下面的question显示错误，和其他的相似页面的显示不一致

**Comment by ChenXuhan** [comment]
问题的tag标签需要进行处理，先在由于未作处理"tags":"<javascript><jquery><textarea><css-transitions>"
把第一个标签<javascript>直接作为html标签处理了

**Comment by luckcul** [comment]
http://192.168.7.117:6789/stackoverflow/showUser?userId=2925963
类似

**Comment by ChenXuhan** [comment]
现在前端改过来了，标签显示目前只是基础版本，比较粗糙。
后端现在有问题，没有返回完整的Question数据
