### ISSUE TITLE
用户能力分析页面skills-general view模块问题

### ISSUE THREAD

**Issue by yeluting** [ACT-Monster/ACT-Show#38]
http://192.168.7.117:6789/topcoder/showUser?userId=16378
skills的general view中，将鼠标放在具体的能力上时，显示的不是相应能力的得分，而是其他技能的得分
skills的detail view中，技能雷达图上数值重叠，不易看清，并感觉将文字放在柱状图上不合适，可改成放在柱状图之后？不显示得分，将鼠标放在相应能力的柱上时显示能力值

**Comment by ChenXuhan** [comment]
你用的是chrome吗？我点开链接的时候没有这个问题，这种issue可以的话也截个图？
技能雷达数值显示重叠的问题，暂定解决方法是：不显示数值，鼠标移动到相应的点上时再显示数值
