### ISSUE TITLE
用户能力分析与challenge页面跳转问题

### ISSUE THREAD

**Issue by yeluting** [ACT-Monster/ACT-Show#39]
http://192.168.7.117:6789/topcoder/showUser?userId=16378
在最下面，不能跳转进具体的challenge中，感觉这里challenge的状态不是那么重要，不需要加红

**Comment by ChenXuhan** [comment]
跳转进具体challenge的链接正在做。
challenge的状态这个可以讨论一下

**Comment by ChenXuhan** [comment]
作为某个人的资源库，这个challenge状态不重要的话，可以考虑删除

**Comment by ChenXuhan** [comment]
链接已完成
