### ISSUE TITLE
数据概览-“Github开发者活跃时间分布”图的部分文字描述不清楚

### ISSUE THREAD

**Issue by hsun2022** [ACT-Monster/ACT-Show#4]
“以commit为指标”不具体，建议改为“commit次数”。

“Github开发者活跃时间分布”，建议改为"Github开发者活跃度分布"

**Comment by ChenXuhan** [comment]
第一条采纳。
活跃度分布，字面理解像是以某一指标衡量活跃度，然后对用户进行分类

**Comment by hsun2022** [comment]
GitHub开发者活跃度的时间分布？

**Comment by ChenXuhan** [comment]
好的，改成“GitHub开发者活跃度的时间分布”
