### ISSUE TITLE
Topcoder 用户搜索结果重复

### ISSUE THREAD

**Issue by ChenXuhan** [ACT-Monster/ACT-Show#42]
http://localhost:8080/searchUser?type=1&content=java&pageId=1&platform=1
与
http://localhost:8080/searchUser?type=1&content=java&pageId=2&platform=1
同时出现了用户sakar2003。
经过多次实验，发现好像是因为每次查询结果顺序不一定的关系，每次返回结果顺序并不同，有时该用户位于第一页，有时位于第二页 #

**Comment by luckcul** [comment]
es中topcoder数据问题，现在应该正确了。
请确认 @ChenXuhan
