### ISSUE TITLE
searchUser的默认设置以及图标点击问题

### ISSUE THREAD

**Issue by Jasmine-DJ-420** [ACT-Monster/ACT-Show#45]
http://192.168.7.117:6789/searchUser
搜索框Please Choose似乎改成默认by profile更好，“please choose”这一项似乎可有可无。
搜索框右侧的放大镜图标似乎设置成可以点击的更好，因为用鼠标操作的时候一般默认可点击图标进行搜索。

**Comment by ChenXuhan** [comment]
输入框输入的时候大家喜欢直接回车进行查询，没必要添加按钮。例如Github的搜索框。

**Comment by hsun2022** [comment]
有一个默认的搜索选项比较好，方便用户 👍

**Comment by ChenXuhan** [comment]
已改成默认by profile
