### ISSUE TITLE
SO技能列表与技能云不匹配

### ISSUE THREAD

**Issue by Runingtime** [ACT-Monster/ACT-Show#51]
http://192.168.7.117:6789/stackoverflow/showUser?userId=8976&url=https://stackoverflow.com/users/8976/ericschaefer

技能云中tdd 584而列表中却没有

**Comment by ChenXuhan** [comment]
经过核查，是由于技能中有特殊字符constructor，在js文件读取的过程中被当做js.constructor属性。现已修改
