### ISSUE TITLE
知识图谱显示问题

### ISSUE THREAD

**Issue by yeluting** [ACT-Monster/ACT-Show#63]
节点信息栏目数与关系信息栏目数一致，是否会比较合适？
每一列的数据 没有说明栏目意义，是否加上比较好？
在图表显示时，未在左侧标出是哪个平台，不够直观，建议在左侧将显示的平台名称变红体字
csdn的关系信息描述与其他平台不一致

**Comment by ChenXuhan** [comment]
已审核

**Comment by zhouqilin1993** [comment]
关系 | 关系描述 | 条数
-- | -- | --
answer_item | 答案qa_answer指向问题qa_question | 259269
author_item | 用户User指向编写的内容(bbs_comment, bbs_ask etc.) | 5806138
blog_comment | 博客评论User指向博客作者user | 41972
comment_item | 博客评论blog_comment指向博客帖子blog | 3831586
forum_follow | 论坛跟贴User指向论坛发帖User | 2740264
qa_answer | 问答答案User指向问答问题User | 208637
qa_comment | 问答评论User指向问答问题User | 54023


CSDN部分 改为这样？
