### ISSUE TITLE
SO用户问题有重复，且问题链接打开已就位当前页

### ISSUE THREAD

**Issue by sunflower93** [ACT-Monster/ACT-Show#9]
在下面页面发现该问题http://192.168.7.117:6789/stackoverflow/showUser?userId=5730919

**Comment by ChenXuhan** [comment]
能够具体描述一下吗？不太理解你的意思

**Comment by sunflower93** [comment]
该用户下面的问题列表中有两个完全相同的问题，且两个问题点击后都是打开该用户页面而非问题页面

**Comment by luckcul** [comment]
问题已修复。
